
<!-- Generated by ai2svelte v0.123.1 - 2025-09-02 08:21 -->
<!-- ai file: beforeAfter.ai -->
<style lang="scss">
#g-beforeAfter-box {
	container-type: inline-size;
	container-name: g-beforeAfter-box;
}
#g-beforeAfter-box,
#g-beforeAfter-box .g-artboard {
	margin: 0 auto;
}
#g-beforeAfter-box p {
	margin: 0;
}
#g-beforeAfter-box .g-aiAbs {
	position: absolute;
}
#g-beforeAfter-box .g-aiImg {
	position: absolute;
	top: 0;
	display: block;
	width: 100% !important;
	height: 100%;
	background-size: contain;
	background-repeat: no-repeat;
}
#g-beforeAfter-box .g-aiSymbol {
	position: absolute;
	box-sizing: border-box;
}
#g-beforeAfter-box .g-aiPointText p {
	white-space: nowrap;
}
@mixin animations($values...) {
        $animation: ();
        @each $value in $values {
            $animation: append($animation, $value, comma);
        }
        animation: $animation;
    }#g-beforeAfter-xs {
	position: relative;
	overflow: hidden;
}
@container g-beforeAfter-box (width >= 510px) {
#g-beforeAfter-xs {
	display: none;
}
}
#g-beforeAfter-sm {
	position: relative;
	overflow: hidden;
}
#g-beforeAfter-sm {
	display: none;
}
@container g-beforeAfter-box (width >= 510px) and (width < 660px) {
#g-beforeAfter-sm {
	display: block;
}
}
#g-beforeAfter-md {
	position: relative;
	overflow: hidden;
}
#g-beforeAfter-md {
	display: none;
}
@container g-beforeAfter-box (width >= 660px) and (width < 930px) {
#g-beforeAfter-md {
	display: block;
}
}
#g-beforeAfter-lg {
	position: relative;
	overflow: hidden;
}
#g-beforeAfter-lg {
	display: none;
}
@container g-beforeAfter-box (width >= 930px) and (width < 1200px) {
#g-beforeAfter-lg {
	display: block;
}
}
#g-beforeAfter-xl {
	position: relative;
	overflow: hidden;
}
#g-beforeAfter-xl {
	display: none;
}
@container g-beforeAfter-box (width >= 1200px) {
#g-beforeAfter-xl {
	display: block;
}
}

/* Custom CSS */


</style>

<script>
	let { assetsPath = '/', onAiMounted = () => {}, slider } = $props();
let width = $state(100);

import { onMount } from 'svelte';
onMount(() => {
  onAiMounted();
});

</script>
<div id="g-beforeAfter-box" class="ai2svelte">
	<!-- Artboard: xs -->
	<div id="g-beforeAfter-xs" class="g-artboard" style="max-width: 509px;aspect-ratio: 0.5028426924154;" data-aspect-ratio="0.503" data-min-width="0" data-max-width="509">
		<div id="g-beforeAfter-xs-img" class="g-beforeAfter-xs-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/beforeAfter-xs.png);" loading="lazy"></div>		<div id="g-png-before-xs" class="g-png-before-xs g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/before-xs.png);" loading="lazy"></div>
		<div id="g-png-after-xs" class="g-png-after-xs g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/after-xs.png);" loading="lazy"></div>
		<div class="g-snippet-layer g-slider">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-slider" data-name="slider" style="width: 92.1212%; height: 2.4533%; margin-left: -46.0606%; margin-top: -2.4394%; background-color: rgb(204,204,204); left: 50%; top: 96.5552%;">
{@render slider?.()}
</div>
		</div>

	</div>
	<!-- Artboard: sm -->
	<div id="g-beforeAfter-sm" class="g-artboard" style="min-width: 510px;max-width: 659px;aspect-ratio: 0.76891895811461;" data-aspect-ratio="0.769" data-min-width="510" data-max-width="659">
		<div id="g-beforeAfter-sm-img" class="g-beforeAfter-sm-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/beforeAfter-sm.png);" loading="lazy"></div>		<div id="g-png-before-sm" class="g-png-before-sm g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/before-sm.png);" loading="lazy"></div>
		<div id="g-png-after-sm" class="g-png-after-sm g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/after-sm.png);" loading="lazy"></div>
		<div class="g-snippet-layer g-slider">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-slider" data-name="slider" style="width: 92.3922%; height: 1.3871%; margin-left: -46.1961%; margin-top: -0.902%; background-color: rgb(204,204,204); left: 50%; top: 96.9219%;">
{@render slider?.()}
</div>
		</div>

	</div>
	<!-- Artboard: md -->
	<div id="g-beforeAfter-md" class="g-artboard" style="min-width: 660px;max-width: 929px;aspect-ratio: 1.19507009903465;" data-aspect-ratio="1.195" data-min-width="660" data-max-width="929">
		<div id="g-beforeAfter-md-img" class="g-beforeAfter-md-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/beforeAfter-md.png);" loading="lazy"></div>		<div id="g-png-before-md" class="g-png-before-md g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/before-md.png);" loading="lazy"></div>
		<div id="g-png-after-md" class="g-png-after-md g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/after-md.png);" loading="lazy"></div>
		<div class="g-snippet-layer g-slider">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-slider" data-name="slider" style="width: 73.9545%; height: 2.4988%; margin-left: -36.9773%; margin-top: -1.0455%; background-color: rgb(204,204,204); left: 50%; top: 94.7093%;">
{@render slider?.()}
</div>
		</div>

	</div>
	<!-- Artboard: lg -->
	<div id="g-beforeAfter-lg" class="g-artboard" style="min-width: 930px;max-width: 1199px;aspect-ratio: 1.41065361623927;" data-aspect-ratio="1.411" data-min-width="930" data-max-width="1199">
		<div id="g-beforeAfter-lg-img" class="g-beforeAfter-lg-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/beforeAfter-lg.png);" loading="lazy"></div>		<div id="g-png-before-lg" class="g-png-before-lg g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/before-lg.png);" loading="lazy"></div>
		<div id="g-png-after-lg" class="g-png-after-lg g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/after-lg.png);" loading="lazy"></div>
		<div class="g-snippet-layer g-slider">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-slider" data-name="slider" style="width: 71.4516%; height: 2.8516%; margin-left: -35.7258%; margin-top: -1.0108%; background-color: rgb(204,204,204); left: 50.0142%; top: 94.5646%;">
{@render slider?.()}
</div>
		</div>

	</div>
	<!-- Artboard: xl -->
	<div id="g-beforeAfter-xl" class="g-artboard" style="min-width: 1200px;aspect-ratio: 1.96399345335516;" data-aspect-ratio="1.964" data-min-width="1200">
		<div id="g-beforeAfter-xl-img" class="g-beforeAfter-xl-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/beforeAfter-xl.png);" loading="lazy"></div>		<div id="g-png-before-xl" class="g-png-before-xl g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/before-xl.png);" loading="lazy"></div>
		<div id="g-png-after-xl" class="g-png-after-xl g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/after-xl.png);" loading="lazy"></div>
		<div class="g-snippet-layer g-slider">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-slider" data-name="slider" style="width: 56%; height: 3.1097%; margin-left: -28%; margin-top: -0.7917%; background-color: rgb(204,204,204); left: 52.1667%; top: 92.4335%;">
{@render slider?.()}
</div>
		</div>

	</div>
</div>

<!-- End ai2svelte - 2025-09-02 08:21 -->
