
<!-- Generated by ai2svelte v0.123.1 - 2025-11-04 14:17 -->
<!-- ai file: fire.ai -->
<style lang="scss">
#g-fire-box {
	container-type: inline-size;
	container-name: g-fire-box;
}
#g-fire-box,
#g-fire-box .g-artboard {
	margin: 0 auto;
}
#g-fire-box p {
	margin: 0;
}
#g-fire-box .g-aiAbs {
	position: absolute;
}
#g-fire-box .g-aiImg {
	position: absolute;
	top: 0;
	display: block;
	width: 100% !important;
	height: 100%;
	background-size: contain;
	background-repeat: no-repeat;
}
#g-fire-box .g-aiSymbol {
	position: absolute;
	box-sizing: border-box;
}
#g-fire-box .g-aiPointText p {
	white-space: nowrap;
}
#g-fire-box.g-aiPointText p { white-space: nowrap; }
#g-fire-box{
container-type: inline-size;
@container (min-width:0px) and (max-width: 659px) {
#g-fire-xs {
display: block !important;
}
}
@container (min-width:660px) and (max-width: 1199px) {
#g-fire-md {
display: block !important;
}
}
@container (min-width:1200px) {
#g-fire-xl {
display: block !important;
}
}
}
#g-fire-xs {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-fire-xs p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 14px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 12px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-fire-xs .g-pstyle0 {
	font-weight: 700;
	height: 14px;
	text-align: center;
}
#g-fire-xs .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	height: 14px;
	text-align: center;
}
#g-fire-md {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-fire-md p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 17px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 14px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-fire-md .g-pstyle0 {
	font-weight: 700;
	height: 17px;
}
#g-fire-md .g-pstyle1 {
	font-weight: 700;
	height: 17px;
	text-align: center;
}
#g-fire-md .g-pstyle2 {
	font-weight: 400;
	font-style: italic;
	height: 17px;
	text-align: center;
}
#g-fire-md .g-pstyle3 {
	font-weight: 700;
	height: 17px;
	text-align: right;
}
#g-fire-xl {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-fire-xl p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 24px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 20px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-fire-xl .g-pstyle0 {
	font-weight: 700;
	height: 24px;
}
#g-fire-xl .g-pstyle1 {
	font-weight: 700;
	height: 24px;
	text-align: center;
}
#g-fire-xl .g-pstyle2 {
	font-weight: 400;
	font-style: italic;
	height: 24px;
	text-align: center;
}
#g-fire-xl .g-pstyle3 {
	font-weight: 700;
	height: 24px;
	text-align: right;
}

/* Custom CSS */
@mixin shadow-havarti($clr){
text-shadow: 0 0 4px rgba($clr, 0.7);
}
.g-text {
  @include shadow-havarti(#000000);
}


</style>

<script>
	let { assetsPath = '/', activeArtboard = $bindable(), onAiMounted = () => {}, onArtboardChange = () => {},  } = $props();
import { onMount, untrack } from 'svelte';
let aiBox;
let aiBoxWidth = $state(undefined);
let allArtboards = $state([]);
onMount(() => {
allArtboards = Array.from(aiBox.querySelectorAll('.g-artboard'));
onAiMounted();
});
$effect(() => {
if (aiBoxWidth) {
const currentArtboard = allArtboards.filter((artboard) => {
const minWidth = parseFloat(artboard.dataset.minWidth);
const maxWidth = parseFloat(artboard.dataset.maxWidth) || Infinity;
return minWidth <= aiBoxWidth && maxWidth >= aiBoxWidth;
})[0];
if (currentArtboard?.id !== activeArtboard?.id) {
activeArtboard = untrack(() => currentArtboard);
onArtboardChange(activeArtboard);
}
}
});

</script>
<div id="g-fire-box" class="ai2svelte"bind:this={aiBox} bind:clientWidth={aiBoxWidth}>
	<!-- Artboard: xs -->
	<div id="g-fire-xs" class="g-artboard" style="max-width: 659px;aspect-ratio: 0.31242045734204;" data-aspect-ratio="0.312" data-min-width="0" data-max-width="659">
		<div id="g-fire-xs-img" class="g-fire-xs-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/fire-xs.png);" loading="lazy"></div>		<div id="g-png-layer-swir-xs" class="g-png-layer-swir g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-swir-xs.png);" loading="lazy"></div>
<svg class="g-fire-xs-arrows-img g-svg-layer" style="position: absolute;width: 100%;height: 100.0029%;top: 0%;left: 0%;" id="g-svg-arrows" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 330 1056.269">
  <!-- Generator: Adobe Illustrator 29.8.2, SVG Export Plug-In . SVG Version: 2.1.1 Build 3)  -->
  <line x1="269.35" y1="618.976" x2="269.193" y2="548.269" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width=".917"/>
  <line x1="54.35" y1="915.976" x2="54.193" y2="845.269" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width=".917"/>
<style>
#g-svg-arrows rect, #g-svg-arrows circle, #g-svg-arrows path, #g-svg-arrows line, #g-svg-arrows polyline, #g-svg-arrows polygon { vector-effect: non-scaling-stroke; }
</style>
</svg>

		<div id="g-ai0-1" class="g-text g-aiAbs g-aiPointText" style="top:51.3598%;margin-top:-7.5px;left:81.5368%;margin-left:-36.5px;width:73px;">
			<p class="g-pstyle0">active fire</p>
		</div>
		<div id="g-ai0-2" class="g-text g-aiAbs g-aiPointText" style="top:68.2305%;margin-top:-14.7px;left:48.0194%;margin-left:-68px;width:136px;">
			<p class="g-pstyle0">Cottonwood Peak Fire</p>
			<p class="g-pstyle1">(Burn scar)</p>
		</div>
		<div id="g-ai0-3" class="g-text g-aiAbs g-aiPointText" style="top:87.3355%;margin-top:-7.5px;left:16.3829%;margin-left:-39px;width:78px;">
			<p class="g-pstyle0">active fires</p>
		</div>
	</div>
	<!-- Artboard: md -->
	<div id="g-fire-md" class="g-artboard" style="min-width: 660px;max-width: 1199px;aspect-ratio: 0.3975259768492;" data-aspect-ratio="0.398" data-min-width="660" data-max-width="1199">
		<div id="g-fire-md-img" class="g-fire-md-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/fire-md.png);" loading="lazy"></div>		<div id="g-png-layer-swir-md" class="g-png-layer-swir g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-swir-md.png);" loading="lazy"></div>
<svg class="g-fire-md-arrows-img g-svg-layer" style="position: absolute;width: 100%;height: 100.0019%;top: 0%;left: 0%;" id="g-svg-arrows" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 660 1660.269">
  <!-- Generator: Adobe Illustrator 29.8.2, SVG Export Plug-In . SVG Version: 2.1.1 Build 3)  -->
  <line x1="491.462" y1="971.46" x2="564.341" y2="971.46" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width="1.417"/>
  <line x1="86.881" y1="1321.483" x2="159.759" y2="1321.483" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width="1.417"/>
<style>
#g-svg-arrows rect, #g-svg-arrows circle, #g-svg-arrows path, #g-svg-arrows line, #g-svg-arrows polyline, #g-svg-arrows polygon { vector-effect: non-scaling-stroke; }
</style>
</svg>

		<div id="g-ai1-1" class="g-text g-aiAbs g-aiPointText" style="top:58.4894%;margin-top:-9.1px;left:86.5469%;width:81px;">
			<p class="g-pstyle0">active fire</p>
		</div>
		<div id="g-ai1-2" class="g-text g-aiAbs g-aiPointText" style="top:67.9095%;margin-top:-17.5px;left:48.5101%;margin-left:-77.5px;width:155px;">
			<p class="g-pstyle1">Cottonwood Peak Fire</p>
			<p class="g-pstyle2">(Burn scar)</p>
		</div>
		<div id="g-ai1-3" class="g-text g-aiAbs g-aiPointText" style="top:79.5703%;margin-top:-9.1px;right:87.5632%;width:88px;">
			<p class="g-pstyle3">active fires</p>
		</div>
	</div>
	<!-- Artboard: xl -->
	<div id="g-fire-xl" class="g-artboard" style="min-width: 1200px;aspect-ratio: 0.52060737527115;" data-aspect-ratio="0.521" data-min-width="1200">
		<div id="g-fire-xl-img" class="g-fire-xl-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/fire-xl.png);" loading="lazy"></div>		<div id="g-png-layer-swir-xl" class="g-png-layer-swir g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-swir-xl.png);" loading="lazy"></div>
<svg class="g-fire-xl-arrows-img g-svg-layer" style="position: absolute;width: 100%;height: 100%;top: 0%;left: 0%;" id="g-svg-arrows" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1200 2305">
  <!-- Generator: Adobe Illustrator 29.8.2, SVG Export Plug-In . SVG Version: 2.1.1 Build 3)  -->
  <line x1="828" y1="1355.269" x2="930.856" y2="1355.269" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width="2"/>
  <line x1="257" y1="1849.269" x2="359.856" y2="1849.269" fill="none" stroke="#fff" stroke-miterlimit="10" stroke-width="2"/>
<style>
#g-svg-arrows rect, #g-svg-arrows circle, #g-svg-arrows path, #g-svg-arrows line, #g-svg-arrows polyline, #g-svg-arrows polygon { vector-effect: non-scaling-stroke; }
</style>
</svg>

		<div id="g-ai2-1" class="g-text g-aiAbs g-aiPointText" style="top:58.7779%;margin-top:-12.8px;left:78.3792%;width:107px;">
			<p class="g-pstyle0">active fire</p>
		</div>
		<div id="g-ai2-2" class="g-text g-aiAbs g-aiPointText" style="top:68.3657%;margin-top:-24.8px;left:48.8951%;margin-left:-106.5px;width:213px;">
			<p class="g-pstyle1">Cottonwood Peak Fire</p>
			<p class="g-pstyle2">(Burn scar)</p>
		</div>
		<div id="g-ai2-3" class="g-text g-aiAbs g-aiPointText" style="top:80.2095%;margin-top:-12.8px;right:79.1707%;width:116px;">
			<p class="g-pstyle3">active fires</p>
		</div>
	</div>
</div>

<!-- End ai2svelte - 2025-11-04 14:17 -->
