
<!-- Generated by ai2svelte v0.123.1 - 2025-08-31 23:14 -->
<!-- ai file: headline.ai -->
<style lang="scss">
#g-headline-box {
	container-type: inline-size;
	container-name: g-headline-box;
}
#g-headline-box,
#g-headline-box .g-artboard {
	margin: 0 auto;
}
#g-headline-box p {
	margin: 0;
}
#g-headline-box .g-aiAbs {
	position: absolute;
}
#g-headline-box .g-aiImg {
	position: absolute;
	top: 0;
	display: block;
	width: 100% !important;
	height: 100%;
	background-size: contain;
	background-repeat: no-repeat;
}
#g-headline-box .g-aiSymbol {
	position: absolute;
	box-sizing: border-box;
}
#g-headline-box .g-aiPointText p {
	white-space: nowrap;
}
@mixin animations($values...) {
        $animation: ();
        @each $value in $values {
            $animation: append($animation, $value, comma);
        }
        animation: $animation;
    }#g-headline-xs {
	position: relative;
	overflow: hidden;
}
@container g-headline-box (width >= 510px) {
#g-headline-xs {
	display: none;
}
}
#g-headline-sm {
	position: relative;
	overflow: hidden;
}
#g-headline-sm {
	display: none;
}
@container g-headline-box (width >= 510px) and (width < 660px) {
#g-headline-sm {
	display: block;
}
}
#g-headline-md {
	position: relative;
	overflow: hidden;
}
#g-headline-md {
	display: none;
}
@container g-headline-box (width >= 660px) and (width < 930px) {
#g-headline-md {
	display: block;
}
}
#g-headline-lg {
	position: relative;
	overflow: hidden;
}
#g-headline-lg {
	display: none;
}
@container g-headline-box (width >= 930px) and (width < 1200px) {
#g-headline-lg {
	display: block;
}
}
#g-headline-xl {
	position: relative;
	overflow: hidden;
}
#g-headline-xl {
	display: none;
}
@container g-headline-box (width >= 1200px) {
#g-headline-xl {
	display: block;
}
}

/* Custom CSS */
@mixin shadow-havarti($clr){
text-shadow: 0 0 4px #000000b3;
}
#g-snippet-hed {
	@include shadow-havarti(#000000);
}



</style>

<script>
	let { assetsPath = '/', onAiMounted = () => {}, hed } = $props();
let width = $state(100);

import { onMount } from 'svelte';
onMount(() => {
  onAiMounted();
});

</script>
<div id="g-headline-box" class="ai2svelte">
	<!-- Artboard: xs -->
	<div id="g-headline-xs" class="g-artboard" style="max-width: 509px;aspect-ratio: 0.44042935462097;" data-aspect-ratio="0.44" data-min-width="0" data-max-width="509">
		<div id="g-headline-xs-img" class="g-headline-xs-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/headline-xs.png);" loading="lazy"></div>		<div class="g-snippet-layer g-hed">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-hed" data-name="hed" style="width: 80.9091%; height: 24.2903%; margin-left: -40.4545%; margin-top: -27.5758%; left: 50.1338%; top: 15.5176%;">
{@render hed?.()}
</div>
		</div>

	</div>
	<!-- Artboard: sm -->
	<div id="g-headline-sm" class="g-artboard" style="min-width: 510px;max-width: 659px;aspect-ratio: 0.57805508469061;" data-aspect-ratio="0.578" data-min-width="510" data-max-width="659">
		<div id="g-headline-sm-img" class="g-headline-sm-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/headline-sm.png);" loading="lazy"></div>		<div class="g-snippet-layer g-hed">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-hed" data-name="hed" style="width: 74.1569%; height: 19.2685%; margin-left: -37.0784%; margin-top: -16.6667%; left: 50%; top: 15.5586%;">
{@render hed?.()}
</div>
		</div>

	</div>
	<!-- Artboard: md -->
	<div id="g-headline-md" class="g-artboard" style="min-width: 660px;max-width: 929px;aspect-ratio: 0.77989399349069;" data-aspect-ratio="0.78" data-min-width="660" data-max-width="929">
		<div id="g-headline-md-img" class="g-headline-md-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/headline-md.png);" loading="lazy"></div>		<div class="g-snippet-layer g-hed">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-hed" data-name="hed" style="width: 73.7576%; height: 15.3615%; margin-left: -36.8788%; margin-top: -9.8485%; left: 50.1283%; top: 13.8572%;">
{@render hed?.()}
</div>
		</div>

	</div>
	<!-- Artboard: lg -->
	<div id="g-headline-lg" class="g-artboard" style="min-width: 930px;max-width: 1199px;aspect-ratio: 1.41065361623927;" data-aspect-ratio="1.411" data-min-width="930" data-max-width="1199">
		<div id="g-headline-lg-img" class="g-headline-lg-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/headline-lg.png);" loading="lazy"></div>		<div class="g-snippet-layer g-hed">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-hed" data-name="hed" style="width: 75.6989%; height: 28.5164%; margin-left: -37.8495%; margin-top: -10.1075%; left: 51.4434%; top: 22.1865%;">
{@render hed?.()}
</div>
		</div>

	</div>
	<!-- Artboard: xl -->
	<div id="g-headline-xl" class="g-artboard" style="min-width: 1200px;aspect-ratio: 1.46520146520147;" data-aspect-ratio="1.465" data-min-width="1200">
		<div id="g-headline-xl-img" class="g-headline-xl-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/headline-xl.png);" loading="lazy"></div>		<div class="g-snippet-layer g-hed">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-hed" data-name="hed" style="width: 85.5%; height: 22.9548%; margin-left: -42.75%; margin-top: -7.8333%; left: 50%; top: 17.8594%;">
{@render hed?.()}
</div>
		</div>

	</div>
</div>

<!-- End ai2svelte - 2025-08-31 23:14 -->
