
<!-- Generated by ai2svelte v0.123.1 - 2025-11-03 23:43 -->
<!-- ai file: mapVideo.ai -->
<style lang="scss">
#g-mapVideo-box {
	container-type: inline-size;
	container-name: g-mapVideo-box;
}
#g-mapVideo-box,
#g-mapVideo-box .g-artboard {
	margin: 0 auto;
}
#g-mapVideo-box p {
	margin: 0;
}
#g-mapVideo-box .g-aiAbs {
	position: absolute;
}
#g-mapVideo-box .g-aiImg {
	position: absolute;
	top: 0;
	display: block;
	width: 100% !important;
	height: 100%;
	background-size: contain;
	background-repeat: no-repeat;
}
#g-mapVideo-box .g-aiSymbol {
	position: absolute;
	box-sizing: border-box;
}
#g-mapVideo-box .g-aiPointText p {
	white-space: nowrap;
}
#g-mapVideo-box.g-aiPointText p { white-space: nowrap; }
#g-mapVideo-box{
container-type: inline-size;
@container (min-width:0px) and (max-width: 509px) {
#g-mapVideo-xs {
display: block !important;
}
}
@container (min-width:510px) and (max-width: 659px) {
#g-mapVideo-sm {
display: block !important;
}
}
@container (min-width:660px) and (max-width: 929px) {
#g-mapVideo-md {
display: block !important;
}
}
@container (min-width:930px) and (max-width: 1199px) {
#g-mapVideo-lg {
display: block !important;
}
}
@container (min-width:1200px) {
#g-mapVideo-xl {
display: block !important;
}
}
}
#g-mapVideo-xs {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-mapVideo-xs p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 17px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 14px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-mapVideo-xs .g-pstyle0 {
	font-weight: 500;
	height: 17px;
}
#g-mapVideo-xs .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	line-height: 14px;
	height: 14px;
	font-size: 12px;
	text-align: center;
	color: rgb(163,163,163);
}
#g-mapVideo-sm {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-mapVideo-sm p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 17px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 14px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-mapVideo-sm .g-pstyle0 {
	font-weight: 500;
	height: 17px;
}
#g-mapVideo-sm .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	height: 17px;
	text-align: center;
	color: rgb(163,163,163);
}
#g-mapVideo-md {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-mapVideo-md p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 19px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 16px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-mapVideo-md .g-pstyle0 {
	font-weight: 500;
	height: 19px;
}
#g-mapVideo-md .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	height: 19px;
	text-align: center;
	color: rgb(163,163,163);
}
#g-mapVideo-lg {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-mapVideo-lg p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 24px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 20px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-mapVideo-lg .g-pstyle0 {
	font-weight: 500;
	height: 24px;
}
#g-mapVideo-lg .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	height: 24px;
	text-align: center;
	color: rgb(163,163,163);
}
#g-mapVideo-xl {
	position: relative;
	overflow: hidden;
	display: none;
}
#g-mapVideo-xl p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-serif;
	font-weight: regular;
	line-height: 24px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 20px;
	text-align: left;
	color: rgb(255,255,255);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-mapVideo-xl .g-pstyle0 {
	font-weight: 500;
	height: 24px;
}
#g-mapVideo-xl .g-pstyle1 {
	font-weight: 400;
	font-style: italic;
	height: 24px;
	text-align: center;
	color: rgb(163,163,163);
}

/* Custom CSS */
@mixin shadow-feta($clr){
text-shadow: 0 0 10px rgba($clr, 0.5), 0 0 3px rgba($clr, 1);
}
.g-text {
  @include shadow-feta(#000000);
}


</style>

<script>
	let { assetsPath = '/', activeArtboard = $bindable(), onAiMounted = () => {}, onArtboardChange = () => {}, vid } = $props();
import { onMount, untrack } from 'svelte';
let aiBox;
let aiBoxWidth = $state(undefined);
let allArtboards = $state([]);
onMount(() => {
allArtboards = Array.from(aiBox.querySelectorAll('.g-artboard'));
onAiMounted();
});
$effect(() => {
if (aiBoxWidth) {
const currentArtboard = allArtboards.filter((artboard) => {
const minWidth = parseFloat(artboard.dataset.minWidth);
const maxWidth = parseFloat(artboard.dataset.maxWidth) || Infinity;
return minWidth <= aiBoxWidth && maxWidth >= aiBoxWidth;
})[0];
if (currentArtboard?.id !== activeArtboard?.id) {
activeArtboard = untrack(() => currentArtboard);
onArtboardChange(activeArtboard);
}
}
});

</script>
<div id="g-mapVideo-box" class="ai2svelte"bind:this={aiBox} bind:clientWidth={aiBoxWidth}>
	<!-- Artboard: xs -->
	<div id="g-mapVideo-xs" class="g-artboard" style="max-width: 509px;aspect-ratio: 0.44042935462097;" data-aspect-ratio="0.44" data-min-width="0" data-max-width="509">
		<div id="g-mapVideo-xs-img" class="g-mapVideo-xs-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/mapVideo-xs.png);" loading="lazy"></div>		<div class="g-snippet-layer g-vid">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-vid" data-name="vid" style="width: 91.0606%; height: 38.5709%; margin-left: -45.5303%; margin-top: -43.7879%; border: 1px solid rgb(142,142,142); left: 50.3923%; top: 49.0127%;">
{@render vid?.()}
</div>
		</div>

		<div id="g-png-layer-anno-dots-xs" class="g-png-layer-anno-dots g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-anno-dots-xs.png);" loading="lazy"></div>
		<div id="g-ai0-1" class="g-text g-aiAbs g-aiPointText" style="top:43.3864%;margin-top:-9.1px;left:38.9542%;width:95px;">
			<p class="g-pstyle0">Gifford Fires</p>
		</div>
		<div id="g-ai0-2" class="g-text g-aiAbs g-aiPointText" style="top:54.197%;margin-top:-9.1px;left:58.7682%;width:94px;">
			<p class="g-pstyle0">Los Angeles</p>
		</div>
		<div id="g-ai0-3" class="g-artwork g-aiAbs g-aiPointText" style="top:83.8815%;margin-top:-7.5px;left:50.3301%;margin-left:-59.5px;width:119px;">
			<p class="g-pstyle1">North Pacific Ocean</p>
		</div>
	</div>
	<!-- Artboard: sm -->
	<div id="g-mapVideo-sm" class="g-artboard" style="min-width: 510px;max-width: 659px;aspect-ratio: 0.57805508469061;" data-aspect-ratio="0.578" data-min-width="510" data-max-width="659">
		<div id="g-mapVideo-sm-img" class="g-mapVideo-sm-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/mapVideo-sm.png);" loading="lazy"></div>		<div class="g-snippet-layer g-vid">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-vid" data-name="vid" style="width: 66.7647%; height: 37.0975%; margin-left: -33.3824%; margin-top: -32.0882%; border: 1px solid rgb(142,142,142); left: 51.8109%; top: 48.5682%;">
{@render vid?.()}
</div>
		</div>

		<div id="g-png-layer-anno-dots-sm" class="g-png-layer-anno-dots g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-anno-dots-sm.png);" loading="lazy"></div>
		<div id="g-ai1-1" class="g-text g-aiAbs g-aiPointText" style="top:43.42%;margin-top:-9.1px;left:42.1815%;width:95px;">
			<p class="g-pstyle0">Gifford Fires</p>
		</div>
		<div id="g-ai1-2" class="g-text g-aiAbs g-aiPointText" style="top:53.621%;margin-top:-9.1px;left:58.1396%;width:94px;">
			<p class="g-pstyle0">Los Angeles</p>
		</div>
		<div id="g-ai1-3" class="g-artwork g-aiAbs g-aiPointText" style="top:81.617%;margin-top:-9.1px;left:33.8471%;margin-left:-67.5px;width:135px;">
			<p class="g-pstyle1">North Pacific Ocean</p>
		</div>
	</div>
	<!-- Artboard: md -->
	<div id="g-mapVideo-md" class="g-artboard" style="min-width: 660px;max-width: 929px;aspect-ratio: 0.77989399349069;" data-aspect-ratio="0.78" data-min-width="660" data-max-width="929">
		<div id="g-mapVideo-md-img" class="g-mapVideo-md-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/mapVideo-md.png);" loading="lazy"></div>		<div class="g-snippet-layer g-vid">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-vid" data-name="vid" style="width: 50.9697%; height: 38.2148%; margin-left: -25.4848%; margin-top: -24.5%; border: 1px solid rgb(142,142,142); left: 53.0741%; top: 49.4086%;">
{@render vid?.()}
</div>
		</div>

		<div id="g-png-layer-anno-dots-md" class="g-png-layer-anno-dots g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-anno-dots-md.png);" loading="lazy"></div>
		<div id="g-ai2-1" class="g-text g-aiAbs g-aiPointText" style="top:43.8589%;margin-top:-10.2px;left:45.2579%;width:106px;">
			<p class="g-pstyle0">Gifford Fires</p>
		</div>
		<div id="g-ai2-2" class="g-text g-aiAbs g-aiPointText" style="top:54.4938%;margin-top:-10.2px;left:57.7407%;width:105px;">
			<p class="g-pstyle0">Los Angeles</p>
		</div>
		<div id="g-ai2-3" class="g-artwork g-aiAbs g-aiPointText" style="top:81.3174%;margin-top:-10.2px;left:24.5684%;margin-left:-75.5px;width:151px;">
			<p class="g-pstyle1">North Pacific Ocean</p>
		</div>
	</div>
	<!-- Artboard: lg -->
	<div id="g-mapVideo-lg" class="g-artboard" style="min-width: 930px;max-width: 1199px;aspect-ratio: 1.41065361623927;" data-aspect-ratio="1.411" data-min-width="930" data-max-width="1199">
		<div id="g-mapVideo-lg-img" class="g-mapVideo-lg-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/mapVideo-lg.png);" loading="lazy"></div>		<div class="g-snippet-layer g-vid">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-vid" data-name="vid" style="width: 29.6129%; height: 40.1505%; margin-left: -14.8065%; margin-top: -14.2312%; border: 1px solid rgb(142,142,142); left: 44.6183%; top: 49.1851%;">
{@render vid?.()}
</div>
		</div>

		<div id="g-png-layer-anno-dots-lg" class="g-png-layer-anno-dots g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-anno-dots-lg.png);" loading="lazy"></div>
		<div id="g-ai3-1" class="g-text g-aiAbs g-aiPointText" style="top:43.3556%;margin-top:-12.8px;left:41.858%;width:127px;">
			<p class="g-pstyle0">Gifford Fires</p>
		</div>
		<div id="g-ai3-2" class="g-text g-aiAbs g-aiPointText" style="top:54.1251%;margin-top:-12.8px;left:47.706%;width:125px;">
			<p class="g-pstyle0">Los Angeles</p>
		</div>
		<div id="g-ai3-3" class="g-artwork g-aiAbs g-aiPointText" style="top:56.7037%;margin-top:-12.8px;left:16.0899%;margin-left:-91.5px;width:183px;">
			<p class="g-pstyle1">North Pacific Ocean</p>
		</div>
	</div>
	<!-- Artboard: xl -->
	<div id="g-mapVideo-xl" class="g-artboard" style="min-width: 1200px;aspect-ratio: 1.46520146520147;" data-aspect-ratio="1.465" data-min-width="1200">
		<div id="g-mapVideo-xl-img" class="g-mapVideo-xl-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/mapVideo-xl.png);" loading="lazy"></div>		<div class="g-snippet-layer g-vid">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-vid" data-name="vid" style="width: 30.25%; height: 42.6129%; margin-left: -15.125%; margin-top: -14.5417%; border: 1px solid rgb(142,142,142); left: 48.7791%; top: 52.2041%;">
{@render vid?.()}
</div>
		</div>

		<div id="g-png-layer-anno-dots-xl" class="g-png-layer-anno-dots g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/layer-anno-dots-xl.png);" loading="lazy"></div>
		<div id="g-ai4-1" class="g-text g-aiAbs g-aiPointText" style="top:46.1331%;margin-top:-12.8px;left:45.1547%;width:127px;">
			<p class="g-pstyle0">Gifford Fires</p>
		</div>
		<div id="g-ai4-2" class="g-artwork g-aiAbs g-aiPointText" style="top:57.2442%;margin-top:-12.8px;left:15.3511%;margin-left:-91.5px;width:183px;">
			<p class="g-pstyle1">North Pacific Ocean</p>
		</div>
		<div id="g-ai4-3" class="g-text g-aiAbs g-aiPointText" style="top:57.6105%;margin-top:-12.8px;left:51.6868%;width:125px;">
			<p class="g-pstyle0">Los Angeles</p>
		</div>
	</div>
</div>

<!-- End ai2svelte - 2025-11-03 23:43 -->
