
<!-- Generated by ai2svelte v0.123.1 - 2025-09-01 12:08 -->
<!-- ai file: stock.ai -->
<style lang="scss">
#g-stock-box {
	container-type: inline-size;
	container-name: g-stock-box;
}
#g-stock-box,
#g-stock-box .g-artboard {
	margin: 0 auto;
}
#g-stock-box p {
	margin: 0;
}
#g-stock-box .g-aiAbs {
	position: absolute;
}
#g-stock-box .g-aiImg {
	position: absolute;
	top: 0;
	display: block;
	width: 100% !important;
	height: 100%;
	background-size: contain;
	background-repeat: no-repeat;
}
#g-stock-box .g-aiSymbol {
	position: absolute;
	box-sizing: border-box;
}
#g-stock-box .g-aiPointText p {
	white-space: nowrap;
}
@mixin animations($values...) {
        $animation: ();
        @each $value in $values {
            $animation: append($animation, $value, comma);
        }
        animation: $animation;
    }#g-stock-xs {
	position: relative;
	overflow: hidden;
}
@container g-stock-box (width >= 510px) {
#g-stock-xs {
	display: none;
}
}
#g-stock-sm {
	position: relative;
	overflow: hidden;
}
#g-stock-sm {
	display: none;
}
@container g-stock-box (width >= 510px) and (width < 660px) {
#g-stock-sm {
	display: block;
}
}
#g-stock-md {
	position: relative;
	overflow: hidden;
}
#g-stock-md {
	display: none;
}
@container g-stock-box (width >= 660px) {
#g-stock-md {
	display: block;
}
}
#g-stock-md p {
	font-family: var(--theme-font-family-sans-serif), Knowledge, sans-;
	font-weight: regular;
	line-height: 14px;
	height: auto;
	opacity: 1;
	letter-spacing: 0em;
	font-size: 12px;
	text-align: left;
	color: rgb(166,166,166);
	text-transform: none;
	padding-bottom: 0;
	padding-top: 0;
	mix-blend-mode: normal;
	font-style: normal;
	position: static;
}
#g-stock-md .g-pstyle0 {
	font-weight: 700;
	line-height: 19px;
	height: 19px;
	font-size: 16px;
	color: rgb(64,64,64);
}
#g-stock-md .g-pstyle1 {
	font-weight: 300;
	height: 14px;
	color: rgb(64,64,64);
}
#g-stock-md .g-pstyle2 {
	font-weight: 300;
	height: 14px;
	text-align: right;
}
#g-stock-md .g-pstyle3 {
	font-weight: 300;
	line-height: 13px;
	height: 13px;
	font-size: 11px;
	color: rgb(102,102,102);
}
#g-stock-md .g-pstyle4 {
	font-weight: 300;
	height: 14px;
	text-align: center;
	color: rgb(123,123,123);
}
#g-stock-md .g-pstyle5 {
	font-weight: 300;
	height: 14px;
	letter-spacing: 0.001em;
	text-align: center;
	color: rgb(123,123,123);
}
#g-stock-md .g-pstyle6 {
	font-weight: 300;
	height: 14px;
	color: rgb(102,102,102);
}
#g-stock-md .g-cstyle0 {
	letter-spacing: 0.02em;
}
#g-stock-md .g-cstyle1 {
	letter-spacing: 0.005em;
}
#g-stock-md .g-cstyle2 {
	letter-spacing: -0.005em;
}
#g-stock-md .g-cstyle3 {
	letter-spacing: -0.004em;
}
#g-stock-md .g-cstyle4 {
	letter-spacing: -0.001em;
}
#g-stock-md .g-cstyle5 {
	letter-spacing: -0.003em;
}
#g-stock-md .g-cstyle6 {
	letter-spacing: -0.007em;
}
#g-stock-md .g-cstyle7 {
	letter-spacing: -0.008em;
}
#g-stock-md .g-cstyle8 {
	letter-spacing: -0.01em;
}
#g-stock-md .g-cstyle9 {
	letter-spacing: -0.002em;
}
#g-stock-md .g-cstyle10 {
	letter-spacing: -0.009em;
}
#g-stock-md .g-cstyle11 {
	letter-spacing: 0.001em;
}
#g-stock-md .g-cstyle12 {
	letter-spacing: 0em;
}
#g-stock-md .g-cstyle13 {
	letter-spacing: 0.008em;
}

/* Custom CSS */


</style>

<script>
	let { assetsPath = '/', onAiMounted = () => {}, ripple, bitcoin, ethereum } = $props();
let width = $state(100);

import { onMount } from 'svelte';
onMount(() => {
  onAiMounted();
});

</script>
<div id="g-stock-box" class="ai2svelte">
	<!-- Artboard: xs -->
	<div id="g-stock-xs" class="g-artboard" style="max-width: 509px;aspect-ratio: 0.44042935462097;" data-aspect-ratio="0.44" data-min-width="0" data-max-width="509">
		<div id="g-stock-xs-img" class="g-stock-xs-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/stock-xs.png);" loading="lazy"></div>


	</div>
	<!-- Artboard: sm -->
	<div id="g-stock-sm" class="g-artboard" style="min-width: 510px;max-width: 659px;aspect-ratio: 0.57805508469061;" data-aspect-ratio="0.578" data-min-width="510" data-max-width="659">
		<div id="g-stock-sm-img" class="g-stock-sm-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/stock-sm.png);" loading="lazy"></div>


	</div>
	<!-- Artboard: md -->
	<div id="g-stock-md" class="g-artboard" style="min-width: 660px;aspect-ratio: 1.73106191194952;" data-aspect-ratio="1.731" data-min-width="660">
		<div id="g-stock-md-img" class="g-stock-md-img g-aiImg" alt="" style="background-image: url({ assetsPath.replace(new RegExp('/([^/.]+)$'), '/$1/') || '/' }images/graphics/stock-md.png);" loading="lazy"></div>		<div class="g-snippet-layer g-ripple">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-ripple" data-name="ripple" style="width: 3.4848%; height: 6.0325%; margin-left: -1.7424%; margin-top: -1.7424%; left: 90.6586%; top: 29.315%;">
{@render ripple?.()}
</div>
		</div>

		<div class="g-snippet-layer g-bitcoin">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-bitcoin" data-name="bitcoin" style="width: 3.4848%; height: 5.5079%; margin-left: -1.7424%; margin-top: -1.5909%; left: 90.204%; top: 63.9362%;">
{@render bitcoin?.()}
</div>
		</div>

		<div class="g-snippet-layer g-ethereum">
			<div class="g-aiSymbol g-aiSnippet" id="g-snippet-ethereum" data-name="ethereum" style="width: 3.4848%; height: 5.5079%; margin-left: -1.7424%; margin-top: -1.5909%; left: 90.6586%; top: 69.4441%;">
{@render ethereum?.()}
</div>
		</div>

		<div id="g-ai2-1" class="g-artwork g-aiAbs g-aiPointText" style="top:4.5018%;margin-top:-10.2px;left:1.3882%;width:298px;">
			<p class="g-pstyle0">C<span class="g-cstyle0">r</span>yptocurren<span class="g-cstyle1">c</span>y pric<span class="g-cstyle1">e</span>s <span class="g-cstyle2">o</span><span class="g-cstyle3">v</span>er the pa<span class="g-cstyle4">s</span>t <span class="g-cstyle2">y</span>ear</p>
		</div>
		<div id="g-ai2-2" class="g-artwork g-aiAbs g-aiPointText" style="top:10.6219%;margin-top:-7.5px;left:3.5473%;width:56px;">
			<p class="g-pstyle1">Bi<span class="g-cstyle5">t</span><span class="g-cstyle4">c</span>oin</p>
		</div>
		<div id="g-ai2-3" class="g-artwork g-aiAbs g-aiPointText" style="top:10.6219%;margin-top:-7.5px;left:11.9563%;width:70px;">
			<p class="g-pstyle1">Ethe<span class="g-cstyle5">r</span>eum</p>
		</div>
		<div id="g-ai2-4" class="g-artwork g-aiAbs g-aiPointText" style="top:10.6219%;margin-top:-7.5px;left:22.5707%;width:54px;">
			<p class="g-pstyle1">Ripp<span class="g-cstyle6">l</span>e</p>
		</div>
		<div id="g-ai2-5" class="g-artwork g-aiAbs g-aiPointText" style="top:17.7035%;margin-top:-7.5px;right:92.795%;width:59px;">
			<p class="g-pstyle2">+500%</p>
		</div>
		<div id="g-ai2-6" class="g-artwork g-aiAbs g-aiPointText" style="top:23.736%;margin-top:-7.5px;right:92.7883%;width:49px;">
			<p class="g-pstyle2">+<span class="g-cstyle5">4</span>50</p>
		</div>
		<div id="g-ai2-7" class="g-artwork g-aiAbs g-aiPointText" style="top:29.2932%;margin-top:-6.7px;left:92.7417%;width:52px;">
			<p class="g-pstyle3">40<span class="g-cstyle7">0.</span><span class="g-cstyle3">0</span>1</p>
		</div>
		<div id="g-ai2-8" class="g-artwork g-aiAbs g-aiPointText" style="top:29.7685%;margin-top:-7.5px;right:92.881%;width:49px;">
			<p class="g-pstyle2">+400</p>
		</div>
		<div id="g-ai2-9" class="g-artwork g-aiAbs g-aiPointText" style="top:35.801%;margin-top:-7.5px;right:92.8654%;width:48px;">
			<p class="g-pstyle2">+350</p>
		</div>
		<div id="g-ai2-10" class="g-artwork g-aiAbs g-aiPointText" style="top:41.8335%;margin-top:-7.5px;right:92.8011%;width:49px;">
			<p class="g-pstyle2">+300</p>
		</div>
		<div id="g-ai2-11" class="g-artwork g-aiAbs g-aiPointText" style="top:47.6037%;margin-top:-7.5px;right:92.7611%;width:49px;">
			<p class="g-pstyle2">+250</p>
		</div>
		<div id="g-ai2-12" class="g-artwork g-aiAbs g-aiPointText" style="top:53.6362%;margin-top:-7.5px;right:92.8466%;width:49px;">
			<p class="g-pstyle2">+<span class="g-cstyle4">2</span>00</p>
		</div>
		<div id="g-ai2-13" class="g-artwork g-aiAbs g-aiPointText" style="top:59.6687%;margin-top:-7.5px;right:92.8466%;width:46px;">
			<p class="g-pstyle2">+150</p>
		</div>
		<div id="g-ai2-14" class="g-artwork g-aiAbs g-aiPointText" style="top:65.7012%;margin-top:-7.5px;right:92.7823%;width:47px;">
			<p class="g-pstyle2">+100</p>
		</div>
		<div id="g-ai2-15" class="g-artwork g-aiAbs g-aiPointText" style="top:66.0127%;margin-top:-6.7px;left:92.7417%;width:47px;">
			<p class="g-pstyle3">8<span class="g-cstyle6">4</span><span class="g-cstyle8">.</span><span class="g-cstyle9">7</span>9</p>
		</div>
		<div id="g-ai2-16" class="g-artwork g-aiAbs g-aiPointText" style="top:69.4223%;margin-top:-6.7px;left:92.7417%;width:46px;">
			<p class="g-pstyle3"><span class="g-cstyle10">7</span>6.93</p>
		</div>
		<div id="g-ai2-17" class="g-artwork g-aiAbs g-aiPointText" style="top:71.7336%;margin-top:-7.5px;right:92.8617%;width:42px;">
			<p class="g-pstyle2">+50</p>
		</div>
		<div id="g-ai2-18" class="g-artwork g-aiAbs g-aiPointText" style="top:77.5039%;margin-top:-7.5px;right:92.7799%;width:36px;">
			<p class="g-pstyle2">&plusmn;0</p>
		</div>
		<div id="g-ai2-19" class="g-artwork g-aiAbs g-aiPointText" style="top:86.7362%;margin-top:-14.7px;left:10.1476%;margin-left:-24px;width:48px;">
			<p class="g-pstyle4"><span class="g-cstyle11">S</span>ep</p>
			<p class="g-pstyle4">2024</p>
		</div>
		<div id="g-ai2-20" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:16.8816%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle5">Oc<span class="g-cstyle12">t</span></p>
		</div>
		<div id="g-ai2-21" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:23.595%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle4">N<span class="g-cstyle5">o</span>v</p>
		</div>
		<div id="g-ai2-22" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:30.2704%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle5">De<span class="g-cstyle12">c</span></p>
		</div>
		<div id="g-ai2-23" class="g-artwork g-aiAbs g-aiPointText" style="top:86.7362%;margin-top:-14.7px;left:37.2614%;margin-left:-24px;width:48px;">
			<p class="g-pstyle4">Jan</p>
			<p class="g-pstyle4">2025</p>
		</div>
		<div id="g-ai2-24" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:43.9641%;margin-left:-20px;width:40px;">
			<p class="g-pstyle4"><span class="g-cstyle3">F</span>eb</p>
		</div>
		<div id="g-ai2-25" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:50.1006%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle4">Mar</p>
		</div>
		<div id="g-ai2-26" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:57.0971%;margin-left:-20px;width:40px;">
			<p class="g-pstyle4">Apr</p>
		</div>
		<div id="g-ai2-27" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:63.473%;margin-left:-21px;width:42px;">
			<p class="g-pstyle4">May</p>
		</div>
		<div id="g-ai2-28" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:70.5911%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle4">Jun</p>
		</div>
		<div id="g-ai2-29" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:77.4838%;margin-left:-18px;width:36px;">
			<p class="g-pstyle4">Jul</p>
		</div>
		<div id="g-ai2-30" class="g-artwork g-aiAbs g-aiPointText" style="top:84.8477%;margin-top:-7.5px;left:83.8197%;margin-left:-21px;width:42px;">
			<p class="g-pstyle4"><span class="g-cstyle5">A</span>ug</p>
		</div>
		<div id="g-ai2-31" class="g-artwork g-aiAbs g-aiPointText" style="top:96.6504%;margin-top:-7.5px;left:2.2237%;width:88px;">
			<p class="g-pstyle6"><span class="g-cstyle11">S</span>ou<span class="g-cstyle5">r</span><span class="g-cstyle4">c</span><span class="g-cstyle13">e</span>: LS<span class="g-cstyle3">E</span>G</p>
		</div>
	</div>
</div>

<!-- End ai2svelte - 2025-09-01 12:08 -->
